### ISSUE TITLE
Some options will not work in programming mode

### ISSUE THREAD

**Issue by YaminoYuki** [RSeidelsohn/license-checker-rseidelsohn#42] opened 2022-06-23 09:12 UTC
Programmatically:
In the InitOpts we have:
` /**
     * Output a summary of the license usage
     */
    summary?: boolean | undefined;`
also
`/**
     * Write the data to a specific file.
     */
    out?: string | undefined;`

but when I call:
` checker.init({
        start: "path to start",
        summary : true,
        out: "filepath",
        .....`

it seems to ignore both summary and out while for start it is working fine

**Comment by RSeidelsohn** [comment] 2023-04-28 10:31
Hi @sportsracer,

sorry, I just saw your message right now. Today is the first "every 2nd friday" where I am allowed to an will work on this OS project, so I'm currently going through some of the issues.
It is absolutely awesome that you want to participate in the development (no worries if you don't, but if you will, this is always more than welcome). This project's code is still a pretty mess and cleaning it up will take way more time than I initially thought it would. But now I can at least say that I have a relatively good understanding of what the code does how and where (still not perfect, though).
I have to have a look at this issue first, as I think that I already fixed it, as there was a duplicate of this issue, but I am not 100% sure.
Otherwise, anything you want to do is nice. I just want you to understand that the source code is still not easy to read and understand. Especially the tests could need some maintenance, and I would love to switch to using Jest, as I have experience with Jest but none with `jenkins-mocha` and `istanbul`.
So feel free to work on anything you want - breaking the code into smaller chunks (while not breaking the tests) is always very welcome!

Cheers, Roman.

**Comment by RSeidelsohn** [comment] 2023-04-28 10:46
Dear @YaminoYuki,

I am sorry for the long delay! Could you possibly test this again and tell me if you still face this issue? I tried all the three options you mention in combination and the result was as expected the summary in the path and filename provided by the `--out` option.

Cheers, Roman.

**Comment by sportsracer** [comment] 2023-05-12 13:11
Hi @RSeidelsohn 

It's great that your company has that policy!

For me, the reported problem was still there on master. The `--out` parameter works correctly from the CLI, but not if you pass it like `init({out: "path", ...})`.

I've attempted a fix in https://github.com/RSeidelsohn/license-checker-rseidelsohn/pull/81 🙏

**Closed** 2023-09-15 11:44 UTC
